[package]
name = "fuck_excel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
inquire = "0.5.2"
chrono = "0.4.23"
